version: '3.8'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - '4563-4599:4563-4599'
      - '8080:8080'
    environment:
      - 'DEFAULT_REGION=eu-west-2'
