AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Formation template 

Globals:
  Function:
    Timeout: 3

Resources:
  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-user/index.handler
      Runtime: nodejs12.x
      MemorySize: 256
      Timeout: 900
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /accounts/user
            Method: get
  ReplayEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/replay-event/index.handler
      Runtime: nodejs12.x
      MemorySize: 256
      Timeout: 900

Outputs:
  GetUserApi:
    Description: "API Gateway endpoint URL for get user function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/accounts/user"
  GetUserFunction:
    Description: "Get User Lambda Function ARN"
    Value: !GetAtt GetUserFunction.Arn
  GetUserFunctionIamRole:
    Description: "Implicit IAM Role created for Get User function"
    Value: !GetAtt GetUserFunctionRole.Arn
